### PR TITLE
Added ability to configure Browsershot driver instance

### PR DESCRIPTION
**Pull request by tjodalv**
I really like your package, but I am currently not able to use it in scenario where my application is running inside Docker container. Underlying package spatie/browsershot is pretty configurable but I am not able to configure it when using your package.
That is why I made this pull request. Basically all I did is put bunch configuration options in the package config file and implemented those config options on Browsershot instance when generating PDF.

If you run chrome browser inside docker container you need add additional configuration flags to chrome binary in order to everything works, for example:

```php
Browsershot::html($html)
    ->setChromePath('/usr/bin/google-chrome')
    ->addChromiumArguments([
        'disable-gpu',
        'disable-dev-shm-usage',
        'disable-setuid-sandbox',
        'no-sandbox'
    ])
```

With this change in pull request these options can be set in pdfable.php config file, like this:

```php
[
    ...
    'browsershot' => [
        'chromium_arguments' => [
            'disable-gpu',
            'disable-dev-shm-usage',
            'disable-setuid-sandbox',
            'no-sandbox'
        ],

        'options' => [
            // This will use new headless mode which is prefered option
            'headless' => 'new'
        ]
    ],
]
```

You can also configure other parameters like binary to node or npm or setting or other puppeteer options.

### CODE REVIEW

**Comment by pxlrbt** [comment]
Hey,

sorry for the delayed response.

I think instead of replicating all the config options Browsershot has, it would make more sense to have a static `BrowsershotDriver::configureBrowsershot()` method, that receives the instance instead and you would configure it in a ServiceProvider or similar. 

What do you think?

**Comment by tjodalv** [comment]
Hi,

Yes we could do it that way also. I see benefit of that approach in that you do not need to maintain documentation for browsershot configuration and in the future if browsershot package adds new features you do not need to implement that new features in pdfable package. Definitely simpler approach and more maintainable. Maybe that should be the way to solve this issue.

**Comment by pxlrbt** [comment]
Could you update the PR?

**Comment by tjodalv** [comment]
Hi
I've updated the PR. Removed driver configuration from config/pdfable.php and added static method to configure Browsershot instance on BrowsershotDriver class.

I am currently not using this package as I was not able to properly load CSS styles when generating PDF. The thing is I am using docker container to create chromium instance that generate PDF so I don't have to bloat my server with chrome and other libraries. But when using that setup I was not able to properly generate PDF with Browsershot::html() method, that this package is use to generate PDF. I am using Browsershot::url('download/pdf/1') and on that URL I am using my PDFable class to render the document.

**Comment by pxlrbt** [comment]
Thank you. I did some small changes and added some docs.

>  I am using Browsershot::url('download/pdf/1') and on that URL I am using my PDFable class to render the document.

You could just create a custom driver to use `::url()`.

**Pull request merged**
